[build-system]
requires = ["setuptools==80.9.0", "wheel>=0.46.3", "packaging>=24"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["drumblender"]

[project]
name = "drumblender"
version = "0.0.1"
requires-python = ">=3.10,<3.13"
dependencies = [
    "auraloss==0.3.0",
    "boto3>=1.26,<2",
    "einops>=0.6,<1",
    "jsonargparse[signatures]>=4.20,<5",
    "lightning-utilities==0.8.0",
    "numpy==1.26.4",
    "pandas==2.2.3",
    "python-dotenv>=1.0,<2",
    "pytorch-lightning==1.9.5",
    "PyYAML>=6,<7",
    "soundfile>=0.12,<1",
    "torch==2.7.1",
    "torchaudio==2.7.1",
    "torchmetrics==0.11.4",
    "torchvision==0.22.1",
    "tqdm>=4.66,<5",
    "wandb>=0.19,<1",
]

[project.scripts]
drumblender = "drumblender.cli:main"
drumblender-dataset = "drumblender.cli:dataset"
drumblender-synth = "drumblender.cli:inference"

[project.optional-dependencies]
dev = ["black", "flake8", "pytest", "pytest-mock", "pyfakefs", "pre-commit", "pytest-cov"]
modal = ["nnAudio>=0.3,<1", "scipy>=1.10,<2"]
modal_new = ["scipy>=1.10,<2", "matplotlib>=3.7,<4"]
